// customTransactions.js

const customTransactions = [
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 165,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "MyFundedFutures123",
        logo_url: "https://myfundedfutures.com/images/mffu/brandicon.svg",
        name: "MyFundedFutures",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://myfundedfutures.com",
      },
    ],
    date: "2024-11-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Prop Firm Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url: "https://myfundedfutures.com/images/mffu/brandicon.svg",
    merchant_entity_id: "MyFundedFutures123",
    merchant_name: "MyFundedFutures",
    name: "MyFundedFutures ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "MyFundedFutures",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "MF12345",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id: "mfj7gRJzAhoR8AdGKXbTEadg4lz6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://myfundedfutures.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 200,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "MyFundedFutures123",
        logo_url: "https://myfundedfutures.com/images/mffu/brandicon.svg",
        name: "MyFundedFutures",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://myfundedfutures.com",
      },
    ],
    date: "2024-12-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Prop Firm Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url: "https://myfundedfutures.com/images/mffu/brandicon.svg",
    merchant_entity_id: "MyFundedFutures123",
    merchant_name: "MyFundedFutures",
    name: "MyFundedFutures ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "MyFundedFutures",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "MF12346",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id: "mfj7gRJzAhoR8AdGK3bT1Eadg4l4z6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://myfundedfutures.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 180,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "MyFundedFutures123",
        logo_url: "https://myfundedfutures.com/images/mffu/brandicon.svg",
        name: "MyFundedFutures",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://myfundedfutures.com",
      },
    ],
    date: "2025-01-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Prop Firm Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url: "https://myfundedfutures.com/images/mffu/brandicon.svg",
    merchant_entity_id: "MyFundedFutures123",
    merchant_name: "MyFundedFutures",
    name: "MyFundedFutures ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "MyFundedFutures",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "MF12347",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id: "mfj7gdfRJzAhoR8AdGKXbTEadg4lz6DUAgMnk2x",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://myfundedfutures.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 150,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "ApexTraderFunding123",
        logo_url:
          "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
        name: "Apex Trader Funding",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://apextraderfunding.com",
      },
    ],
    date: "2025-02-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Apex Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
    merchant_entity_id: "ApexTraderFunding123",
    merchant_name: "ApexTraderFunding",
    name: "ApexTraderFunding ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "ApexTraderFunding",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "ATF12345",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id: "mfj7gRJzAhoR8AdGKXbasdfTEadg4lz6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://apextraderfunding.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 175,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "TopstepTrader123",
        logo_url:
          "https://www.topstep.com/wp-content/uploads/2023/12/1S1R-new-200px.png",
        name: "Topstep",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://topsteptrader.com",
      },
    ],
    date: "2025-03-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Topstep Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://www.topstep.com/wp-content/uploads/2023/12/1S1R-new-200px.png",
    merchant_entity_id: "TopstepTrader123",
    merchant_name: "TopstepTrader",
    name: "TopstepTrader ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "TopstepTrader",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "TST12345",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id: "mfj7gRJzAho2asdfxR8AdGKXbTEadg4lz6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://topsteptrader.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 190,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "TradeifyFunding123",
        logo_url:
          "https://tradeify.co/wp-content/uploads/2021/06/horizontal-logo.svg",
        name: "Tradeify Funding",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://tradeifyfunding.com",
      },
    ],
    date: "2025-04-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Tradeify Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://tradeify.co/wp-content/uploads/2021/06/horizontal-logo.svg",
    merchant_entity_id: "TradeifyFunding123",
    merchant_name: "TradeifyFunding",
    name: "Tradeify Funding",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "TradeifyFunding",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "TF12345",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id:
      "mfj7sgRJz4Ahosf4g112sRadgd8AdGKXbTEadg4lz6DUAgMn23432423saf2343asdfasfkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://tradeifyfunding.com",
  },

  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 190,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "TradeifyFunding123",
        logo_url:
          "https://tradeify.co/wp-content/uploads/2021/06/horizontal-logo.svg",
        name: "Tradeify Funding",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://tradeifyfunding.com",
      },
    ],
    date: "2025-04-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Tradeify Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://tradeify.co/wp-content/uploads/2021/06/horizontal-logo.svg",
    merchant_entity_id: "TradeifyFunding123",
    merchant_name: "TradeifyFunding",
    name: "Tradeify Funding",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "TradeifyFunding",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "TF12345",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://myfundedfutures.com/images/mffu/brandicon.svg",
    transaction_code: null,
    transaction_id: "mfj7gRJzAhosf4gsRadgd8AdGKXbTE23adg4lz6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://tradeifyfunding.com",
  },
  // Add more custom transactions here
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 200,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "ApexTraderFunding123",
        logo_url:
          "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
        name: "Apex Trader Funding",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://apextraderfunding.com",
      },
    ],
    date: "2025-05-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Apex Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
    merchant_entity_id: "ApexTraderFunding123",
    merchant_name: "ApexTraderFunding",
    name: "ApexTraderFunding ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "ApexTraderFunding",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "ATF12346",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
    transaction_code: null,
    transaction_id: "mfj7gRJzAhoR8AdGKXbTEadg4lz6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://apextraderfunding.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 200,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "ApexTraderFunding123",
        logo_url:
          "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
        name: "Apex Trader Funding",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://apextraderfunding.com",
      },
    ],
    date: "2025-05-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Apex Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
    merchant_entity_id: "ApexTraderFunding123",
    merchant_name: "ApexTraderFunding",
    name: "ApexTraderFunding ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "ApexTraderFunding",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "ATF12346",
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: {
      confidence_level: "VERY_HIGH",
      detailed: "INVESTMENTS_TRADING_PLATFORMS",
      primary: "INVESTMENTS",
    },
    personal_finance_category_icon_url:
      "https://apextraderfunding.com/assets/2024/images/apex-logo-stack-light.png",
    transaction_code: null,
    transaction_id: "mfj7gRJzAhoR2348AdGKXbTEadg4lz6DUAgMnkx",
    transaction_type: "service",
    unofficial_currency_code: null,
    website: "https://apextraderfunding.com",
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 180,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "TopstepTrader123",
        logo_url:
          "https://www.topstep.com/wp-content/uploads/2023/12/1S1R-new-400px.png",
        name: "Topstep",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://topsteptrader.com",
      },
    ],
    date: "2025-06-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Topstep Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://www.topstep.com/wp-content/uploads/2023/12/1S1R-new-200px.png",
    merchant_entity_id: "TopstepTrader123",
    merchant_name: "TopstepTrader",
    name: "TopstepTrader ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "TopstepTrader",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "TST12346",
    },
    pending: false,
    pending_transaction_id: null,
  },
  {
    account_id: "BGbmB1L56kIoJjwmLEd4TPKq81Kp9Et4JvX8M",
    account_owner: null,
    amount: 180,
    authorized_date: null,
    authorized_datetime: null,
    category: ["Investments", "Trading Platforms"],
    category_id: "15005000",
    check_number: null,
    counterparties: [
      {
        confidence_level: "VERY_HIGH",
        entity_id: "TopstepTrader123",
        logo_url:
          "https://www.topstep.com/wp-content/uploads/2023/12/1S1R-new-200px.png",
        name: "Topstep",
        phone_number: "123-456-7890",
        type: "merchant",
        website: "https://topsteptrader.com",
      },
    ],
    date: "2025-06-18",
    datetime: null,
    iso_currency_code: "USD",
    location: {
      address: "123 Topstep Lane",
      city: "New York",
      country: "US",
      lat: 40.7128,
      lon: -74.006,
      postal_code: "10001",
      region: "NY",
      store_number: null,
    },
    logo_url:
      "https://www.topstep.com/wp-content/uploads/2023/12/1S1R-new-200px.png",
    merchant_entity_id: "TopstepTrader123",
    merchant_name: "TopstepTrader",
    name: "TopstepTrader ",
    payment_channel: "online",
    payment_meta: {
      by_order_of: null,
      payee: "TopstepTrader",
      payer: null,
      payment_method: "Credit Card",
      payment_processor: "Stripe",
      ppd_id: null,
      reason: "Monthly ",
      reference_number: "TST12346",
    },
    pending: false,
    pending_transaction_id: null,
  },
];

export default customTransactions;
